[placeholders]
chip-name = { prompt = "Enter chip name", default = "STM32F411RE", type = "string" }
chip-hal-name = { prompt = "Enter chip name in embassy-stm32 HAL", default = "stm32f411re", type = "string" }
chip-arch = { prompt = "Enter chip arch", default = "thumbv7em-none-eabi", type = "string" }
flash-size = { prompt = "Enter flask size (K)", default = "16", type = "string" }
hse-freq = { prompt = "Enter HSE freq", default = "8000000", type = "string" }
board-hash = { prompt = "Enter board hash id", default = "0", type = "string" }
can = { prompt = "Enter can peripheral", default = "CAN1", type = "string" }
can-tx = { prompt = "Enter can tx pin", default = "PA0", type = "string" }
can-rx = { prompt = "Enter can rx pin", default = "PA1", type = "string" }
can2 = { prompt = "Enter can peripheral", default = "CAN1", type = "string" }
can2-tx = { prompt = "Enter can tx pin", default = "PA0", type = "string" }
can2-rx = { prompt = "Enter can rx pin", default = "PA1", type = "string" }
can-baudrate = { prompt = "Enter can baudrate", default = "1000000", type = "string" }

[template]
exclude = ["Cargo.lock", "target"]
