cargo-features = ["panic-immediate-abort"]

[package]
name = "stm32-bootloader"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "boot"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
defmt = { version = "1.0.1", optional = true }
embassy-futures = "0.1.2"
embassy-stm32 = { version = "0.5.0", features = ["{{ chip-hal-name }}", "time", "time-driver-tim1"] }
embassy-time = { version = "0.5.0", features = ["generic-queue-8"] }
embedded-can = { version = "0.4.1", optional = true }
rtt-target = { version = "0.6.2", features = ["defmt"], optional = true }

[features]
rtt = ["dep:rtt-target"]
defmt = [
    "rtt",
    "dep:defmt",
    "embassy-futures/defmt",
    "embassy-stm32/defmt",
    "embassy-time/defmt"
]
hse = []
can = []
can2 = []
smps_power = []
fdcan = ["dep:embedded-can"]
rtt-host-to-chip = ["rtt"]
external-octo-spi-flash = ["rtt-host-to-chip"]
external-flash = ["rtt-host-to-chip"]
external-macronix-octo-spi-flash = ["external-flash"]

[profile.dev]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "immediate-abort"
debug = 2

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "immediate-abort"
debug = 2
